preset: psr2

risky: false

enabled:
  - no_unused_imports
  - no_useless_else
  - phpdoc_add_missing_param_annotation
  - phpdoc_no_package
  - phpdoc_scalar
  - phpdoc_types
  - unix_line_endings


linting: true

finder:
  name:
    - "*.php"
  not-name:
    - "*.html.php"
  path:
    - "src"
    - "lib"
    - "tests"
  not-path:
    - "build"
    - "public"
    - "vendor"
